/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.parser;

import prolixa.node.*;
import prolixa.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTThis(@SuppressWarnings("unused") TThis node)
    {
        this.index = 0;
    }

    @Override
    public void caseTIs(@SuppressWarnings("unused") TIs node)
    {
        this.index = 1;
    }

    @Override
    public void caseTProgram(@SuppressWarnings("unused") TProgram node)
    {
        this.index = 2;
    }

    @Override
    public void caseTLet(@SuppressWarnings("unused") TLet node)
    {
        this.index = 3;
    }

    @Override
    public void caseTUs(@SuppressWarnings("unused") TUs node)
    {
        this.index = 4;
    }

    @Override
    public void caseTBegin(@SuppressWarnings("unused") TBegin node)
    {
        this.index = 5;
    }

    @Override
    public void caseTThatMaiusculo(@SuppressWarnings("unused") TThatMaiusculo node)
    {
        this.index = 6;
    }

    @Override
    public void caseTWould(@SuppressWarnings("unused") TWould node)
    {
        this.index = 7;
    }

    @Override
    public void caseTBe(@SuppressWarnings("unused") TBe node)
    {
        this.index = 8;
    }

    @Override
    public void caseTAll(@SuppressWarnings("unused") TAll node)
    {
        this.index = 9;
    }

    @Override
    public void caseTIt(@SuppressWarnings("unused") TIt node)
    {
        this.index = 10;
    }

    @Override
    public void caseTPresents(@SuppressWarnings("unused") TPresents node)
    {
        this.index = 11;
    }

    @Override
    public void caseTAlterable(@SuppressWarnings("unused") TAlterable node)
    {
        this.index = 12;
    }

    @Override
    public void caseTUnalterable(@SuppressWarnings("unused") TUnalterable node)
    {
        this.index = 13;
    }

    @Override
    public void caseTJust(@SuppressWarnings("unused") TJust node)
    {
        this.index = 14;
    }

    @Override
    public void caseTIn(@SuppressWarnings("unused") TIn node)
    {
        this.index = 15;
    }

    @Override
    public void caseTCase(@SuppressWarnings("unused") TCase node)
    {
        this.index = 16;
    }

    @Override
    public void caseTThatMinusculo(@SuppressWarnings("unused") TThatMinusculo node)
    {
        this.index = 17;
    }

    @Override
    public void caseTAs(@SuppressWarnings("unused") TAs node)
    {
        this.index = 18;
    }

    @Override
    public void caseTLong(@SuppressWarnings("unused") TLong node)
    {
        this.index = 19;
    }

    @Override
    public void caseTConsidering(@SuppressWarnings("unused") TConsidering node)
    {
        this.index = 20;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 21;
    }

    @Override
    public void caseTAnswer(@SuppressWarnings("unused") TAnswer node)
    {
        this.index = 22;
    }

    @Override
    public void caseTAnswerValores(@SuppressWarnings("unused") TAnswerValores node)
    {
        this.index = 23;
    }

    @Override
    public void caseTSymbol(@SuppressWarnings("unused") TSymbol node)
    {
        this.index = 24;
    }

    @Override
    public void caseTIdentificador(@SuppressWarnings("unused") TIdentificador node)
    {
        this.index = 25;
    }

    @Override
    public void caseTVector(@SuppressWarnings("unused") TVector node)
    {
        this.index = 26;
    }

    @Override
    public void caseTFrom(@SuppressWarnings("unused") TFrom node)
    {
        this.index = 27;
    }

    @Override
    public void caseTTo(@SuppressWarnings("unused") TTo node)
    {
        this.index = 28;
    }

    @Override
    public void caseTBy(@SuppressWarnings("unused") TBy node)
    {
        this.index = 29;
    }

    @Override
    public void caseTDo(@SuppressWarnings("unused") TDo node)
    {
        this.index = 30;
    }

    @Override
    public void caseTOf(@SuppressWarnings("unused") TOf node)
    {
        this.index = 31;
    }

    @Override
    public void caseTOtherwise(@SuppressWarnings("unused") TOtherwise node)
    {
        this.index = 32;
    }

    @Override
    public void caseTGo(@SuppressWarnings("unused") TGo node)
    {
        this.index = 33;
    }

    @Override
    public void caseTNext(@SuppressWarnings("unused") TNext node)
    {
        this.index = 34;
    }

    @Override
    public void caseTIteration(@SuppressWarnings("unused") TIteration node)
    {
        this.index = 35;
    }

    @Override
    public void caseTCapture(@SuppressWarnings("unused") TCapture node)
    {
        this.index = 36;
    }

    @Override
    public void caseTShow(@SuppressWarnings("unused") TShow node)
    {
        this.index = 37;
    }

    @Override
    public void caseTAbandon(@SuppressWarnings("unused") TAbandon node)
    {
        this.index = 38;
    }

    @Override
    public void caseTAbreParenteses(@SuppressWarnings("unused") TAbreParenteses node)
    {
        this.index = 39;
    }

    @Override
    public void caseTFechaParenteses(@SuppressWarnings("unused") TFechaParenteses node)
    {
        this.index = 40;
    }

    @Override
    public void caseTAbreColchetes(@SuppressWarnings("unused") TAbreColchetes node)
    {
        this.index = 41;
    }

    @Override
    public void caseTFechaColchetes(@SuppressWarnings("unused") TFechaColchetes node)
    {
        this.index = 42;
    }

    @Override
    public void caseTAbreChaves(@SuppressWarnings("unused") TAbreChaves node)
    {
        this.index = 43;
    }

    @Override
    public void caseTFechaChaves(@SuppressWarnings("unused") TFechaChaves node)
    {
        this.index = 44;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 45;
    }

    @Override
    public void caseTIntermedioVetor(@SuppressWarnings("unused") TIntermedioVetor node)
    {
        this.index = 46;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 47;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 48;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 49;
    }

    @Override
    public void caseTPontoFinal(@SuppressWarnings("unused") TPontoFinal node)
    {
        this.index = 50;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 51;
    }

    @Override
    public void caseTBarraVertical(@SuppressWarnings("unused") TBarraVertical node)
    {
        this.index = 52;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 53;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 54;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 55;
    }

    @Override
    public void caseTVinculacao(@SuppressWarnings("unused") TVinculacao node)
    {
        this.index = 56;
    }

    @Override
    public void caseTNotEqual(@SuppressWarnings("unused") TNotEqual node)
    {
        this.index = 57;
    }

    @Override
    public void caseTLessEqual(@SuppressWarnings("unused") TLessEqual node)
    {
        this.index = 58;
    }

    @Override
    public void caseTGreaterEqual(@SuppressWarnings("unused") TGreaterEqual node)
    {
        this.index = 59;
    }

    @Override
    public void caseTLess(@SuppressWarnings("unused") TLess node)
    {
        this.index = 60;
    }

    @Override
    public void caseTGreater(@SuppressWarnings("unused") TGreater node)
    {
        this.index = 61;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 62;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 63;
    }

    @Override
    public void caseTTimes(@SuppressWarnings("unused") TTimes node)
    {
        this.index = 64;
    }

    @Override
    public void caseTDivide(@SuppressWarnings("unused") TDivide node)
    {
        this.index = 65;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 66;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 67;
    }

    @Override
    public void caseTXor(@SuppressWarnings("unused") TXor node)
    {
        this.index = 68;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 69;
    }

    @Override
    public void caseTIntDivide(@SuppressWarnings("unused") TIntDivide node)
    {
        this.index = 70;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 71;
    }
}
