/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ABoolExp extends PExp
{
    private TAnswerValores _answerValores_;

    public ABoolExp()
    {
        // Constructor
    }

    public ABoolExp(
        @SuppressWarnings("hiding") TAnswerValores _answerValores_)
    {
        // Constructor
        setAnswerValores(_answerValores_);

    }

    @Override
    public Object clone()
    {
        return new ABoolExp(
            cloneNode(this._answerValores_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolExp(this);
    }

    public TAnswerValores getAnswerValores()
    {
        return this._answerValores_;
    }

    public void setAnswerValores(TAnswerValores node)
    {
        if(this._answerValores_ != null)
        {
            this._answerValores_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._answerValores_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._answerValores_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._answerValores_ == child)
        {
            this._answerValores_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._answerValores_ == oldChild)
        {
            setAnswerValores((TAnswerValores) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
