/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ACaptureComando extends PComando
{
    private final LinkedList<PVar> _variaveis_ = new LinkedList<PVar>();

    public ACaptureComando()
    {
        // Constructor
    }

    public ACaptureComando(
        @SuppressWarnings("hiding") List<?> _variaveis_)
    {
        // Constructor
        setVariaveis(_variaveis_);

    }

    @Override
    public Object clone()
    {
        return new ACaptureComando(
            cloneList(this._variaveis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaptureComando(this);
    }

    public LinkedList<PVar> getVariaveis()
    {
        return this._variaveis_;
    }

    public void setVariaveis(List<?> list)
    {
        for(PVar e : this._variaveis_)
        {
            e.parent(null);
        }
        this._variaveis_.clear();

        for(Object obj_e : list)
        {
            PVar e = (PVar) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._variaveis_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variaveis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variaveis_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PVar> i = this._variaveis_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVar) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
