/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AJustInCaseComando extends PComando
{
    private PExp _condicao_;
    private final LinkedList<PComando> _corpo_ = new LinkedList<PComando>();

    public AJustInCaseComando()
    {
        // Constructor
    }

    public AJustInCaseComando(
        @SuppressWarnings("hiding") PExp _condicao_,
        @SuppressWarnings("hiding") List<?> _corpo_)
    {
        // Constructor
        setCondicao(_condicao_);

        setCorpo(_corpo_);

    }

    @Override
    public Object clone()
    {
        return new AJustInCaseComando(
            cloneNode(this._condicao_),
            cloneList(this._corpo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJustInCaseComando(this);
    }

    public PExp getCondicao()
    {
        return this._condicao_;
    }

    public void setCondicao(PExp node)
    {
        if(this._condicao_ != null)
        {
            this._condicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicao_ = node;
    }

    public LinkedList<PComando> getCorpo()
    {
        return this._corpo_;
    }

    public void setCorpo(List<?> list)
    {
        for(PComando e : this._corpo_)
        {
            e.parent(null);
        }
        this._corpo_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._corpo_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condicao_)
            + toString(this._corpo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condicao_ == child)
        {
            this._condicao_ = null;
            return;
        }

        if(this._corpo_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condicao_ == oldChild)
        {
            setCondicao((PExp) newChild);
            return;
        }

        for(ListIterator<PComando> i = this._corpo_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
