/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private TIdentificador _identificador_;
    private PDeclaracoes _secaoDeclaracoes_;
    private PComandos _secaoComandos_;

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PDeclaracoes _secaoDeclaracoes_,
        @SuppressWarnings("hiding") PComandos _secaoComandos_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setSecaoDeclaracoes(_secaoDeclaracoes_);

        setSecaoComandos(_secaoComandos_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneNode(this._identificador_),
            cloneNode(this._secaoDeclaracoes_),
            cloneNode(this._secaoComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PDeclaracoes getSecaoDeclaracoes()
    {
        return this._secaoDeclaracoes_;
    }

    public void setSecaoDeclaracoes(PDeclaracoes node)
    {
        if(this._secaoDeclaracoes_ != null)
        {
            this._secaoDeclaracoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secaoDeclaracoes_ = node;
    }

    public PComandos getSecaoComandos()
    {
        return this._secaoComandos_;
    }

    public void setSecaoComandos(PComandos node)
    {
        if(this._secaoComandos_ != null)
        {
            this._secaoComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secaoComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._secaoDeclaracoes_)
            + toString(this._secaoComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._secaoDeclaracoes_ == child)
        {
            this._secaoDeclaracoes_ = null;
            return;
        }

        if(this._secaoComandos_ == child)
        {
            this._secaoComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._secaoDeclaracoes_ == oldChild)
        {
            setSecaoDeclaracoes((PDeclaracoes) newChild);
            return;
        }

        if(this._secaoComandos_ == oldChild)
        {
            setSecaoComandos((PComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
