/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import java.util.*;
import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AShowComando extends PComando
{
    private final LinkedList<PExp> _expressoes_ = new LinkedList<PExp>();

    public AShowComando()
    {
        // Constructor
    }

    public AShowComando(
        @SuppressWarnings("hiding") List<?> _expressoes_)
    {
        // Constructor
        setExpressoes(_expressoes_);

    }

    @Override
    public Object clone()
    {
        return new AShowComando(
            cloneList(this._expressoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAShowComando(this);
    }

    public LinkedList<PExp> getExpressoes()
    {
        return this._expressoes_;
    }

    public void setExpressoes(List<?> list)
    {
        for(PExp e : this._expressoes_)
        {
            e.parent(null);
        }
        this._expressoes_.clear();

        for(Object obj_e : list)
        {
            PExp e = (PExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expressoes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressoes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExp> i = this._expressoes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
