/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TThatMaiusculo extends Token
{
    public TThatMaiusculo()
    {
        super.setText("That");
    }

    public TThatMaiusculo(int line, int pos)
    {
        super.setText("That");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThatMaiusculo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThatMaiusculo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThatMaiusculo text.");
    }
}
