/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TThatMinusculo extends Token
{
    public TThatMinusculo()
    {
        super.setText("that");
    }

    public TThatMinusculo(int line, int pos)
    {
        super.setText("that");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThatMinusculo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThatMinusculo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThatMinusculo text.");
    }
}
